// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

// Package copygen contains the setup information for copygen generated code.
package copygen

import (
	"github.com/darkLord19/copygen-poc/models"
)

// OKRToObjective copies a models.OKR to a *models.Objective.
func OKRToObjective(tO *models.Objective, fO models.OKR) {
	// *models.Objective fields
	tO.XId = fO.XId
	tO.Name = fO.Name
	tO.HasChildren = fO.HasChildren
	tO.Type = fO.Type
	tO.KeyResultIds = fO.KeyResultIds
	tO.ContributeToProgress = fO.ContributeToProgress
}

// OKRToKeyResult copies a models.OKR to a *models.KeyResult.
func OKRToKeyResult(tK *models.KeyResult, fO models.OKR) {
	// *models.KeyResult fields
	tK.XId = fO.XId
	tK.Name = fO.Name
	tK.HasChildren = fO.HasChildren
	tK.Type = fO.Type
	tK.Outcome = fO.Outcome
}
